// src/builds.js
// Tauma: Criando a lista de builds inicial para facilitar a manutenção
// Aqui colocamos os dados de cada build que aparecerá nos cartões

export const listaBuilds = [
    {
        id: 1,
        versao: "3.28",
        titulo: "Heavy Strike Berserker - OP Stun Build!",
        comentario: "Uma build focada em stunar bosses com facilidade.",
        autor: "Inner Blaze",
        autorSocial: "https://youtube.com/innerblaze",
        data: "Maio 8, 2026",
        tags: ["Mapper", "Bosser", "Starter"],
        linkPob: "https://pobb.in/8SGeFHOzrGVr",
        ascendencia: "berserker"
    },
    {
        id: 2,
        versao: "3.28",
        titulo: "Poison Assassin - Speed Clear",
        comentario: "Build extremamente rápida para limpar mapas.",
        autor: "SirBonksALot",
        autorSocial: "https://twitter.com/sirbonks",
        data: "Maio 10, 2026",
        tags: ["Mapper", "MF"],
        linkPob: "https://pobb.in/OutroLink",
        ascendencia: "assassin"
    },
    {
        id: 3,
        versao: "3.28",
        titulo: "Mana Guardian - Tanky Aura",
        comentario: "Suporte focado em dar muita sobrevivência para o grupo.",
        autor: "GuardianMaster",
        autorSocial: "https://twitch.tv/guardian",
        data: "Maio 11, 2026",
        tags: ["Aurabot"],
        linkPob: "https://pobb.in/LinkMana",
        ascendencia: "guardian"
    },
    {
        id: 4,
        versao: "3.28",
        titulo: "Explosive Arrow Champion",
        comentario: "Build sólida de totems para progredir no jogo.",
        autor: "Zizaran",
        autorSocial: "https://youtube.com/zizaran",
        data: "Maio 12, 2026",
        tags: ["Mapper", "Bosser", "Starter"],
        linkPob: "https://pobb.in/EAChampion",
        ascendencia: "champion"
    },
    {
        id: 5,
        versao: "3.28",
        titulo: "Deadeye Ice Shot",
        comentario: "O clássico arqueiro de gelo para MF.",
        autor: "Grimro",
        autorSocial: "https://twitter.com/grimro",
        data: "Maio 12, 2026",
        tags: ["Mapper", "MF"],
        linkPob: "https://pobb.in/IceShot",
        ascendencia: "deadeye"
    },
    {
        id: 6,
        versao: "3.28",
        titulo: "Boneshatter Juggernaut",
        comentario: "Build corpo a corpo extremamente tanky.",
        autor: "Carn",
        autorSocial: "https://twitch.tv/carn",
        data: "Maio 12, 2026",
        tags: ["Mapper", "Delve", "Starter"],
        linkPob: "https://pobb.in/Boneshatter",
        ascendencia: "juggernaut"
    },
    {
        id: 7,
        versao: "3.28",
        titulo: "Shockwave Totem Hierophant",
        comentario: "Especialista em fazer Sanctum sem ser tocado.",
        autor: "CaptainLance",
        autorSocial: "https://youtube.com/captainlance",
        data: "Maio 12, 2026",
        tags: ["Sanctum", "Bosser"],
        linkPob: "https://pobb.in/Shockwave",
        ascendencia: "hierophant"
    },
    {
        id: 8,
        versao: "3.28",
        titulo: "Toxic Rain Pathfinder",
        comentario: "Confortável, rápida e com frascos infinitos.",
        autor: "Palsteron",
        autorSocial: "https://youtube.com/palsteron",
        data: "Maio 12, 2026",
        tags: ["Mapper", "Heist Farmer"],
        linkPob: "https://pobb.in/TRPathfinder",
        ascendencia: "pathfinder"
    },
    {
        id: 9,
        versao: "3.28",
        titulo: "Righteous Fire Chieftain",
        comentario: "Build para jogar com uma mão só enquanto assiste Netflix.",
        autor: "Pohx",
        autorSocial: "https://pohx.net",
        data: "Maio 12, 2026",
        tags: ["Mapper", "Lab/Trial Runner"],
        linkPob: "https://pobb.in/RFChieftain",
        ascendencia: "chieftain"
    },
    {
        id: 10,
        versao: "3.28",
        titulo: "Penance Brand Inquisitor",
        comentario: "Dano massivo para deletar qualquer boss do jogo.",
        autor: "TheGamer",
        autorSocial: "https://youtube.com/user10",
        data: "Maio 12, 2026",
        tags: ["Bosser", "Sanctum"],
        linkPob: "https://pobb.in/Penance",
        ascendencia: "inquisitor"
    },
    // Tauma: Adicionando mais 10 builds como placeholder para testar o sistema de páginas
    {
        id: 11,
        versao: "3.28",
        titulo: "Build Placeholder 11",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Mapper"],
        linkPob: "#",
        ascendencia: "slayer"
    },
    {
        id: 12,
        versao: "3.28",
        titulo: "Build Placeholder 12",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Bosser"],
        linkPob: "#",
        ascendencia: "trickster"
    },
    {
        id: 13,
        versao: "3.28",
        titulo: "Build Placeholder 13",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["MF"],
        linkPob: "#",
        ascendencia: "occultist"
    },
    {
        id: 14,
        versao: "3.28",
        titulo: "Build Placeholder 14",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Aurabot"],
        linkPob: "#",
        ascendencia: "necromancer"
    },
    {
        id: 15,
        versao: "3.28",
        titulo: "Build Placeholder 15",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Delve"],
        linkPob: "#",
        ascendencia: "saboteur"
    },
    {
        id: 16,
        versao: "3.28",
        titulo: "Build Placeholder 16",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Heist Farmer"],
        linkPob: "#",
        ascendencia: "elementalist"
    },
    {
        id: 17,
        versao: "3.28",
        titulo: "Build Placeholder 17",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Sanctum"],
        linkPob: "#",
        ascendencia: "gladiator"
    },
    {
        id: 18,
        versao: "3.28",
        titulo: "Build Placeholder 18",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Mapper"],
        linkPob: "#",
        ascendencia: "warden"
    },
    {
        id: 19,
        versao: "3.28",
        titulo: "Build Placeholder 19",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Bosser"],
        linkPob: "#",
        ascendencia: "inquisitor"
    },
    {
        id: 20,
        versao: "3.28",
        titulo: "Build Placeholder 20",
        comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        autor: "Autor Teste",
        autorSocial: "#",
        data: "Maio 12, 2026",
        tags: ["Starter"],
        linkPob: "#",
        ascendencia: "juggernaut"
    }
];
